"use strict";
exports.__esModule = true;
exports.categoryRoutes = void 0;
var express_1 = require("express");
var categoryController_1 = require("../controllers/categoryController");
var authMiddleware_1 = require("../middleware/authMiddleware");
var router = express_1["default"].Router();
exports.categoryRoutes = router;
router.route("/").get(authMiddleware_1.auth, categoryController_1.getCategories).post(authMiddleware_1.auth, authMiddleware_1.admin, categoryController_1.createCategory);
router.put("/:id", categoryController_1.updateCategories, authMiddleware_1.auth, authMiddleware_1.admin);
